import mysql from 'mysql2/promise';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

async function cloneData() {
    console.log('🚀 Iniciando clonación de datos (Top 10 Clientes)...');

    const sourceConfig = {
        host: 'localhost',
        user: process.env.DB_USER || 'root',
        password: process.env.DB_PASSWORD || '',
        database: 'imv_crm' // Siempre forzar origen Producción
    };

    const targetConfig = {
        ...sourceConfig,
        database: 'imv_crm_test'
    };

    const conn = await mysql.createConnection(sourceConfig);
    let targetConn;
    
    try {
        // 1. Obtener IDs de los 10 primeros clientes
        const [rows] = await conn.execute('SELECT id FROM clients ORDER BY id ASC LIMIT 10');
        const clientIds = (rows as any[]).map(r => r.id);

        if (clientIds.length === 0) {
            console.error('❌ No se encontraron clientes en la DB origen.');
            return;
        }

        const idsString = clientIds.join(',');
        console.log(`📋 Clientes seleccionados ID: ${idsString}`);

        // 2. Ejecutar inserciones cruzadas (Cross-Database Insert)
        // MySQL permite: INSERT INTO db2.table SELECT * FROM db1.table
        
        // Tablas completas (Configuración/Globales)
        const fullTables = ['roles', 'users', 'service_plans', 'system_settings', 'technicians', 'user_roles'];
        
        // Tablas dependientes de cliente
        const clientTables = [
            'clients', // ID IN (...)
            'contacts', // client_id
            'additional_services', // client_id
            'interactions', // client_id
            'payments',  // client_id
            'products_sold', // client_id
            'service_transfers' // client_id (verificar columna exacta)
        ];

        // Tablas dependientes de Instalación (Si payment depende de installation, está cubierto por client_id en Payment usualmente, pero Installation es clave)
        // Installation tiene client_id.
        clientTables.push('installations');

        targetConn = await mysql.createConnection(targetConfig);
        
        // Desactivar FK checks
        await targetConn.query('SET FOREIGN_KEY_CHECKS=0');

        console.log('🧹 Limpiando DB destino...');
        // Truncar todo primero
        const [allTables] = await targetConn.query('SHOW TABLES');
        for (const t of (allTables as any[])) {
            const tableName = Object.values(t)[0];
            await targetConn.query(`TRUNCATE TABLE \`${tableName}\``);
        }

        console.log('📦 Copiando Tablas Globales...');
        for (const table of fullTables) {
            try {
                // Verificar si tabla existe en origen
                await conn.query(`SELECT 1 FROM ${table} LIMIT 1`);
                await targetConn.query(`INSERT INTO ${targetConfig.database}.${table} SELECT * FROM ${sourceConfig.database}.${table}`);
                console.log(`   ✅ ${table}`);
            } catch (e) {
                console.warn(`   ⚠️ Tabla ${table} omitida (no existe o error).`);
            }
        }

        console.log('📦 Copiando Clientes y Datos Relacionados...');
        
        // Clients
        await targetConn.query(`INSERT INTO clients SELECT * FROM ${sourceConfig.database}.clients WHERE id IN (${idsString})`);
        console.log('   ✅ clients');

        // Tablas directas con client_id
        const simpleClientTables = ['contacts', 'additional_services', 'interactions', 'installations', 'payments', 'products_sold', 'service_transfers'];
        
        for (const table of simpleClientTables) {
            try {
                 // Check if table exists
                await conn.query(`SELECT 1 FROM ${table} LIMIT 1`);
                 // Check column name usually 'client_id' or 'clientId' depending on naming strategy. 
                 // TypeORM defaul naming strategy: camelCase properties -> snake_case columns usually? 
                 // Based on user entities, relations are properties. TypeORM typically uses `clientId` or `client_id`.
                 // Let's check metadata or guess. Convention `client_id` is standard in SQL generated by TypeORM default naming, 
                 // but `clientId` if column name specified.
                 
                 // Let's assume clientId or client_id. I will try both or inspect.
                 const [cols] = await conn.query(`SHOW COLUMNS FROM ${table} LIKE 'client%'`);
                 const colName = (cols as any[])[0]?.Field; // e.g. 'clientId'

                 if (colName) {
                     await targetConn.query(`INSERT INTO ${targetConfig.database}.${table} SELECT * FROM ${sourceConfig.database}.${table} WHERE ${colName} IN (${idsString})`);
                     console.log(`   ✅ ${table}`);
                 } else {
                     console.warn(`   ⚠️ Tabla ${table} saltada (no se encontró columna de cliente).`);
                 }

            } catch (e) {
                console.warn(`   ⚠️ Tabla ${table} omitida (error).`, e);
            }
        }

        // 3. Tablas Nivel 2 (Product Installments)
        // Dependen de products_sold.
        try {
            console.log('📦 Copiando Detalles Profundos (Cuotas)...');
            // Select IDs of products sold copied
            const [prods] = await targetConn.query('SELECT id FROM products_sold');
            const prodIds = (prods as any[]).map(r => r.id);
            
            if (prodIds.length > 0) {
                const pIds = prodIds.join(',');
                // Check column name for product_sold relation inside product_installments
                const [cols] = await conn.query(`SHOW COLUMNS FROM product_installments LIKE 'product%'`);
                 const colName = (cols as any[])[0]?.Field; // e.g. 'productSoldId'
                 
                 if (colName) {
                    await targetConn.query(`INSERT INTO ${targetConfig.database}.product_installments SELECT * FROM ${sourceConfig.database}.product_installments WHERE ${colName} IN (${pIds})`);
                    console.log(`   ✅ product_installments`);
                 }
            }
        } catch (e) {
             console.warn(`   ⚠️ Tabla product_installments omitida.`, e);
        }

        // Reactivar FK
        await targetConn.query('SET FOREIGN_KEY_CHECKS=1');
        
        console.log('✨ Clonación completada con éxito.');

    } catch (error) {
        console.error('❌ Error fatal:', error);
    } finally {
        if (targetConn) await targetConn.end();
        await conn.end();
    }
}

cloneData();
